@extends('layout.layoutpages')
@section('content')
   <section class="block">
       <div class="container">
            <div class="row">
                <div class="col-lg-12"> 
                    <ol>
                        <li style="text-align: left;">Bu beyan {{$salon->salon_adi}}'in gizlilik politikasını ve Kişisel Verilerin Korunmasına ilişkin yasal aydınlatma yükümlülüğünü içerir. {{$salon->salon_adi}}, siteyi ziyaret eden kullanıcıların, bireysel ve kurumsal anlamda gizliliğini korumak ve sitede sunulan tüm hizmetlerden en iyi şekilde faydalanmasının sağlanabilmesi amacıyla; bilgi ve veri güvenliği için çeşitli ilkeler benimsemiştir. Bu gizlilik ilkeleri; {{$salon->salon_adi}} ve bağlı tüm siteler, mobil uygulamaları ve tüm alt hizmetler üzerinde veri toplanması ve/veya kullanımı konusunda uygulanmak üzere belirlenmiş ve beyan edilmektedir. {{$salon->salon_adi}} ve mobil uygulamalarını kullanmakla bu ilkelerin tümü Kullanıcılar tarafından kabul edilmiş addolunur.</li>
                        <li style="text-align: left;">{{$salon->salon_adi}} üyelik aşamasında ve daha sonrasında sizden bazı kişisel bilgilerinizi talep eder. Kişisel bilgilerinizin korunması ve gizliliğinizin sürdürülebilmesi {{$salon->salon_adi}} ekibi olarak birinci önceliğimizdir. Bu nedenle vermiş olduğunuz bilgiler Kullanıcı Sözleşmesi’nde belirtilen kurallar ve amaçlar dışında herhangi bir kapsamda kullanılmayacak, üçüncü şahıslarla paylaşılmayacaktır.</li>
                        <li style="text-align: left;">{{$salon->salon_adi}} için kullanıcılarının güvenliği ve gizliliği en ön planda tutulmaktadır. Kullanıcıların sisteme girmiş olduğu bilgiler, gizlilik ve güven içinde, ayrıca bu verilerin kritik olduğunun bilincinde olarak, en güncel ve en gelişmiş güvenlik teknolojileri kullanılarak korunmaktadır. Ayrıca, sektörel gelişmeler ve veri güvenliği alanındaki gelişen tehlikeler, sürekli olarak takip edilerek ve düzenli testler yürütülerek olası saldırılara ve veri hırsızlığı teşebbüslerine karşı en yüksek düzeyde koruma sağlanmaktadır.</li>
                        <li style="text-align: left;">Kullanıcıların, sistemdeki hesaplarına erişim SSL (Secure Socket Layer) teknolojisi kullanılarak üçüncü kişilerden saklanır. SSL teknolojisi, sunucu ile kullanıcının internet tarayıcısı arasında, kimlik doğrulama ve bağlantı şifreleme gibi iki temel görev üstlenir.</li>
                        <li style="text-align: left;">{{$salon->salon_adi}} kullanıcının isteği dışında ticari iletişim faaliyeti yapmamayı, izin alınmaksızın pazarlama yapmamayı, kullanıcının sistemden ücretsiz ve kolayca çıkabilmesini sağlayacak araçlar sunmayı beyan ve taahhüt eder.</li>
                        <li style="text-align: left;">Sistemle ilgili sorunların tespiti ve söz konusu sorunların en hızlı şekilde giderilebilmesi için, {{$salon->salon_adi}} gerektiğinde kullanıcıların IP adresini tespit etmekte ve bunu kullanmaktadır. IP adresleri, kullanıcıları genel bir şekilde tanımlamak ve kapsamlı demografik bilgi toplamak amacıyla da kullanılabilir.</li>
                        <li style="text-align: left;">{{$salon->salon_adi}}’in 5651 sayılı yasada ve bağlı yönetmeliklerde belirtilen trafik verisi saklama yükümlülükleri ile 213 sayılı Vergi Usul Kanunu ve bağlı yönetmeliklerde belirtilen işlem verisi saklama yükümlülükleri ayrıca saklıdır.</li>
                        <li style="text-align: left;">{{$salon->salon_adi}} sağladığı hizmet içerisinden ve mobil uygulamalarından başkaca sitelere link (bağlantı) sağlayabilir. Anlaşmalı olduğu 3. Partilerin reklamlarını, başvuru formlarını, duyurularını, anketlerini yayınlayabilir. {{$salon->salon_adi}} Kullanıcıları bu formlar, duyurular, anketler ve reklamlar aracılığıyla reklamveren veya anlaşmalı 3. partilerin sitelerine / hizmetlerine / mobil uygulamalarına yönlendirebilir. {{$salon->salon_adi}} bu link (bağlantı) yoluyla erişilen diğer sitelerin ve/veya mobil uygulamaların gizlilik uygulama ve politikalarına, ayrıca barındırdıkları görsel, metinsel her tür içeriklerine ilişkin olarakhiç bir sorumluluk taşımamaktadır.</li>
                        <li style="text-align: left;">Kullanıcılar, site üzerinden bağlantı sağlanan üçüncü kişi ve kurumlara ait sitelerde bulunan hesaplarının gizlilik ve güvenliğinden kendisi sorumludur. Bu üçüncü tarafların gizlilik politikasından {{$salon->salon_adi}} sorumlu tutulamaz.</li>
                        <li style="text-align: left;">Kullanıcılar, site üzerindeki hesap ve şifrelerinin güvenliğinden ve gizliliğinden kendisi sorumludur. Sitenin kullanımı sırasında veya hizmet alımı sırasında herhangi bir verinin yedeklenmemesinden, zarar görmesinden veya herhangi bir kişisel verinin zarar görmesinden doğacak zararlardan {{$salon->salon_adi}} sorumlu değildir.</li>
                        <li style="text-align: left;">Kullanıcıya ait bireysel / kurumsal bilgiler, ad ve soy ad, adres, telefon numarası, elektronik posta adresi ve kullanıcıyı tanımlamaya yönelik diğer her türlü bilgi olarak anlaşılır. {{$salon->salon_adi}} işbu gizlilik bildiriminde aksi belirtilmedikçe bireysel / kurumsal bilgilerden herhangi birini üçüncü kişilere hiç bir şekilde açıklamayacaktır. {{$salon->salon_adi}} aşağıda sayılan hallerde ise işbu gizlilik bildirimi hükümleri dışına çıkarak kullanıcılara ait bilgileri üçüncü kişilere açıklayabilecektir. Bu durumlar;
                    <ol>
                        <li>Yürürlükte bulunan mevzuat ve iç hukukta da etkili uluslararası anlaşmalardaki yasal zorunluluklarauyulmasının gerektiği haller,</li>
                        <li>{{$salon->salon_adi}}'in kullanıcılarıyla arasındaki sözleşmelerin gereklerinin yerine getirilmesi ve bunların uygulamaya konulmalarıyla ilgili hallerde,</li>
                        <li>Yetkili idari ve/veya adli makamlar tarafından usuli yöntemine uygun olarak yürütülen bir araştırma veya soruşturma doğrultusunda kullanıcılarla ilgili bilgi talep edilmesi hallerinde,</li>
                        <li>Kullanıcıların haklarını veya güvenliklerini koruma amacıyla bilgi verilmesinin gerekli olduğu hallerde.</li>
                    </ol>
                    </li>
                        <li style="text-align: left;">{{$salon->salon_adi}} kendisine verilen gizli bilgileri kesinlikle özel ve gizli tutmayı, bunu bir sır olarak saklamayı yükümlülük olarak kabul ettiğini ve gizliliğin sağlanıp sürdürülmesi, gizli bilginin tamamının veya herhangi bir parçasının kamu alanına girmesini veya yetkisiz kullanımını veya üçüncü bir kişiye açıklanmasını önleme gereği olan gerekli tüm teknik, hukuki ve yönetimsel tedbirleri almayı ve üzerine düşen tüm özeni tam olarak göstermeyi işbu bildirimle taahhüt etmektedir.</li>
                        <li style="text-align: left;">Sitede ücretli olarak sunulan bir hizmetten faydalanılması durumunda veya sitede yayınlanan ilanlar üzerinden satın alma yapıldığı durumlarda, Kullanıcıların, Site üzerinden yaptıkları alışverişler sırasında ödeme kuruluşu veya ödeme aracısı üzerinden toplanan kredi kartı bilgileri, satın alınan ürün ve hizmetlerin faturalandırılması amacıyla kullanılabilmektedir.</li>
                        <li style="text-align: left;">Online olarak kredi kartı ile verilen siparişlerin ödeme/fatura/teslimat adresi bilgilerinin güvenilirliği {{$salon->salon_adi}} tarafından Kredi Kartları Dolandırıcılığı’na karşı denetlenmektedir. Bu sebeple, ilk defa sipariş veren bazı Kullanıcı’ların öncelikle finansal ve adres/telefon bilgilerinin doğruluğunun onaylanması gerekebilir. Bu bilgilerin kontrolü için gerekirse kredi kartı sahibi Kullanıcı ile veya ilgili banka ile irtibata geçilebilir.</li>
                        <li style="text-align: left;">{{$salon->salon_adi}} göndereceği e-postalarda, hiç bir şekilde kredi kartı numarası, kullanıcı adı, şifre veya parola talep etmez. E-postalarda yer alan veriler üçüncü şahıslar tarafından görülebilir. {{$salon->salon_adi}} Kullanıcı e-postalarından aktarılan bilgilerin güvenliğini hiçbir koşulda garanti edemez.</li>
                        <li style="text-align: left;">{{$salon->salon_adi}} kullanıcıların web sitesi ve mobil uygulamalardaki kullanım bilgilerini, teknik bir iletişim dosyası olan çerezler (Cookie) kullanarak, Uygulama kullanımı hakkındaki bilgileri IP ya da Sosyal Ağ hesabı kullanıcı verileri ile elde edebilir. Çerez denilen teknik iletişim dosyası, internet sitesini zamansal oranlamalı olarak kaç kişinin kullandığını, bir kişinin ilgili internet sitesini hangi amaçla, kaç kez ziyaret ettiği ve ne kadar kaldığı hakkında istatistiki bilgiler elde etmeye ve kullanıcılar için özel olarak tasarlanmış kullanıcı sayfalarından dinamik çeşitlilikle reklam ve içerik üretilmesine yardımcı olmak üzere tasarlanan ve kullanılan veri dosyasıdır. Kullanıcılar dilerlerse çerezlerin bilgisayarlarına yerleştirilmemesi veya bu türden bir dosyasının gönderildiğinde ikaz verilmesini sağlayacak biçimde tarayıcılarının ayarlarını her zaman değiştirebilirler.</li>
                        <li style="text-align: left;">{{$salon->salon_adi}} tarafından site ya da Uygulamalar içerisinde düzenlenebilecek periyodik veya periyodik olmayan anketlere cevap veren, veya yardım masasına (help desk) soru soran kullanıcılardan talep edilebilecek bilgiler de, {{$salon->salon_adi}} ve işbirliği içindeki kişi ya da kurumlar tarafından bu kullanıcılara doğrudan pazarlama yapmak, istatistiki analizler yapmak ve özel bir veri tabanı oluşturmak amacıyla da kullanılabilmektedir. Anketler veya yardım masası, anlaşma gereği 3. Partiler tarafından sunulan hizmetler olabilir.</li>
                        <li style="text-align: left;">6698 sayılı Kişisel Verilerin İşlenmesi Hakkında Kanun uyarınca, elde edilen kişisel veriler {{$salon->salon_adi}} tarafından, hukuka ve dürüstlük kuralına uygun, güncel, meşru amaçlar için, ölçülü ve ilgili mevzuata uygun sürelerle işlenebilir.</li>
                        <li style="text-align: left;">Elde edilen kişisel veriler, yurtiçi veya yurtdışında {{$salon->salon_adi}}'in çalıştığı hizmet servis sağlayıcılarının tesisi bulunan başka bir ülkede ilgili mevzuat ve öngörülen güvenlik önlemleri dahilinde veriler aktarılabilir, depolanabilir, işlenebilir.</li>
                        <li style="text-align: left;">Kişisel veriler, (i) Kanunlarda açıkça öngörülmesi, (ii) Bir sözleşmenin kurulması veya ifasıyla doğrudan doğruya ilgili olması kaydıyla sözleşmenin taraflarına ait kişisel verilerin işlenmesinin gerekli olması, (iii) Veri sorumlusunun hukuki yükümlülüğünü yerine getirebilmesi için zorunlu olması, (iv) İlgili kişinin kendisi tarafından alenileştirilmiş olması sebeplerinden biri veya birkaçı ile kişisel veri sahibinin rızası alınmaya gerek olmaksızın işlenebilir.</li>
                        <li style="text-align: left;">Gizlilik politikamız ile ilgili her türlü soru, öneri veya üyelik iptal işlemi için <a href="mailto:info@{{$salon->salon_adi}}">info@{{$salon->salon_adi}}</a> mail adresine ileti gönderiniz.</li>
                        <li style="text-align: left;">İşbu Gizlilik/Kişisel Verilerin Korunması Politikası ve İletişim İzni, Türkiye Cumhuriyeti kanunlarına tabidir. Gizlilik/Kişisel Verilerin Korunması Politikası ve İletişim İzni’nin uygulanmasından doğabilecek her türlü uyuşmazlığın çözümünde İzmir Merkez Mahkeme ve İcra Daireleri yetkilidir.</li>
                        <li style="text-align: left;">İşbu Gizlilik/Kişisel Verilerin Korunması Politikası ve İletişim İzni’ni kabul etmekle, bizimle paylaşılmasına rıza göstermiş olduğunuz kişisel verilerinizin, tarafınıza çeşitli avantajların sağlanıp sunulabilmesi ve size özel tanıtım, promosyon, reklam, satış, pazarlama, anket ve benzer amaçlı her türlü elektronik iletişimin telefon, kısa mesaj (SMS), e-posta ve benzeri yollarla yapılması ve diğer iletişim mesajlarının gönderilmesi amacıyla; toplanmasına, saklanmasına, işlenmesine, kullanılmasına ve {{$salon->salon_adi}} sözleşme ilişkisi içerisinde olduğu üçüncü kişilere aktarımına izin vermiş bulunmaktasınız.</li>
                    </ol>
                </div>
            </div>

            
        </div>
   </section>

@endsection