server {
    listen 89.252.140.44:80;
    server_name goztepeaile.randevumcepte.com.tr;
    
    charset off;
    index index.php index.html;
    disable_symlinks if_not_owner from=$root_path;
    access_log /var/www/httpd-logs/laravel_subdomains.access.log;
    error_log /var/www/httpd-logs/laravel_subdomains.error.log notice;
    ssi on;
    set $root_path /var/www/www-root/data/www/randevumcepteyenilaravel/public;
    root $root_path;
    gzip on;
    gzip_comp_level 5;
    gzip_disable "msie6";
    gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/javascript image/svg+xml;
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_index index.php;
        fastcgi_param PHP_ADMIN_VALUE "sendmail_path = /usr/sbin/sendmail -t -i -f webmaster@randevumcepte.com.tr";
        fastcgi_pass unix:/var/www/php-fpm/9.sock;
        fastcgi_split_path_info ^((?U).+\.ph(?:p\d*|tml))(/?.+)$;
        try_files $uri =404;
    }
}
server {
    listen 89.252.140.44:443;
    server_name goztepeaile.randevumcepte.com.tr;
    
    ssl_certificate "/etc/letsencrypt/live/goztepeaile.randevumcepte.com.tr/fullchain.pem";
	ssl_certificate_key "/etc/letsencrypt/live/goztepeaile.randevumcepte.com.tr/privkey.pem";
	ssl_ciphers EECDH:+AES256:-3DES:RSA+AES:!NULL:!RC4;
	ssl_prefer_server_ciphers on;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
	ssl_dhparam /etc/ssl/certs/dhparam4096.pem;
    
    charset off;
    index index.php index.html;
    disable_symlinks if_not_owner from=$root_path;
    access_log /var/www/httpd-logs/laravel_subdomains.access.log;
    error_log /var/www/httpd-logs/laravel_subdomains.error.log notice;
    ssi on;
    set $root_path /var/www/www-root/data/www/randevumcepteyenilaravel/public;
    root $root_path;
    gzip on;
    gzip_comp_level 5;
    gzip_disable "msie6";
    gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/javascript image/svg+xml;
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_index index.php;
        fastcgi_param PHP_ADMIN_VALUE "sendmail_path = /usr/sbin/sendmail -t -i -f webmaster@randevumcepte.com.tr";
        fastcgi_pass unix:/var/www/php-fpm/9.sock;
        fastcgi_split_path_info ^((?U).+\.ph(?:p\d*|tml))(/?.+)$;
        try_files $uri =404;
    }
}
