;[custom-ext-not-reiachable]
;exten => 33,1,Progress()
;exten => 33,n,Set(audio=${SHELL(node /opt/aws-nodejs-sample/script.js --mp3=/var/lib/asterisk/sounds/audio1.mp3 --text='${myMesage}' --wav=/var/lib/asterisk/sounds/audio1.wav)})
;exten => 33,n,Playback(audio1)
;exten => 33,n,Hangup()

[from-internal-custom]
;:internal extension of [polly-simple]
exten => 33,1,Goto(polly-simple,s,1)
exten => 1,1,Goto(randevu-hatirlatma,s,1)
;can be referenced by creating a Custom Destination
Target= polly-simple,s,1
Description= A simple Amazon Polly test
[polly-simple]
exten => s,1,NoOp(Entering Polly-Simple Context)
exten => s,1,Answer()
exten => s,n,Set(Msg=${myMessage})
exten => s,n,AGI(/var/lib/asterisk/agi-bin/pollysimple.php,${Msg})
exten => s,n,Hangup()


[randevu-hatirlatma]
exten => s,1,NoOp(Randevu Hatirlatma)
exten => s,1,Answer()
exten => s,n,Set(Msg=${myMessage})
exten => s,n,AGI(/var/lib/asterisk/agi-bin/pollysimple.php,${Msg}) ;hatırlatma anonsunu çal
exten => s,n,Goto(randevu-secim-menu,s,1)

[randevu-secim-menu]
exten => s,1,NoOp(Randevu Seçim Menüsü)
exten => s,n,WaitExten(5)  ; 5 saniye giriş bekle
exten => 1,1,NoOp(1 Tuşlandı)
exten => 1,1,AGI(/var/lib/asterisk/agi-bin/randevuyagelinecek.php,${randevuid})
exten => 1,1,GotoIf($["${AGISTATUS}"="SUCCESS"]?success:failure)
exten => 1,1(success),AGI(/var/lib/asterisk/agi-bin/pollysimple.php,Bildiriminiz tarafımıza ulaşmıştır. İyi günler dileriz)
exten => 1,1,Hangup()
exten => 2,1,NoOp(2 Tuşlandı)
exten => 2,1,Goto(randevu-guncelleme-menu,s,1)

[randevu-guncelleme-menu]
exten => s,1,NoOp(Randevu Güncelleme Menüsü)
exten => s,1,AGI(/var/lib/asterisk/agi-bin/uygunrandevubul.php,${randevuid})
exten => s,1,AGI(/var/lib/asterisk/agi-bin/pollysimple.php,${uygunrandevu})
exten => 1,1,AGI(/var/lib/asterisk/agi-bin/randevuguncelle.php,${randevuid},${uygunrandevutarih},${uygunrandevusaat})
exten => 1,1,GotoIf($["${AGISTATUS}"="SUCCESS"]?success:failure)
exten => 1,1,(success),AGI(/var/lib/asterisk/agi-bin/pollysimple.php,Randevunuz ${uygunrandevutarih} saat ${uygunrandevusaat} olarak başarıyla güncellenmiştir. İyi günler dileriz.)
exten => 1,1,Hangup()
exten => 2,1,AGI(/var/lib/asterisk/agi-bin/pollysimple.php,Sizi operatöre aktarıyorum)
exten => 2,1,Queue(${$kuyruk},t)
exten => 2,1,Hangup()



;Geçerli olmayan tuşa basıldı

;exten => t,1,NoOp(Eksik veya hatalı bir tuşlama yapıldı)
;exten => t,n,Set(Msg=Eksik veya hatalı bir tuşlama yaptınız.)
;exten => t,n,AGI(/var/lib/asterisk/agi-bin/pollysimple.php,${Msg})
;exten => t,n,WaitExten(5)
;tekrar tuşlama yapılmazsa
;exten => t,n,NoOp(Tuşlama yapılmadı veya gene hatalı tuşlama)
;exten => t,n,Hangup()

[from-trunk-custom]
exten => _X.,1,NoOp(Gelen çağrı trunktan)
exten => _X.,n,Answer()
exten => _X.,n,AGI(/var/lib/asterisk/agi-bin/karsilama_yeni.php)
;exten => _X.,n,AGI(/var/lib/asterisk/agi-bin/pollysimple.php,Arama nedeninizi bir kaç kelime ile söyler misiniz)
;exten => _X.,n,AGI(/var/lib/asterisk/agi-bin/sesliyanit.php)
exten => _X.,n,WaitExten(5) ;5 sn bekle
exten => 0,1,NoOp(0 a basıldı,${operatorkanali} kuyruğuna aktarıldı)
;exten => 0,n,Queue(${operatorkanali},t,30,5)
exten => 0,n,Dial(PJSIP/31)
exten => 0,n,Hangup()